name: Build and Push Docker image

on:
  push:
    branches:
      - main   # sadece main branch'e push olduğunda çalışır
      # istersen tüm branch'ler için "*" yazabilirsin
  workflow_dispatch:  # manuel tetikleme için eklendi

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-most-frequent-english-words:latest
